### ISSUE TITLE
Add travis CI support for running tests continuously 

### ISSUE THREAD

**Issue by nikos** [otto-de/tesla-examples#5]
It would be great if the tesla examples would be automatically tested on every check-in, this can be achieved for example with Travis CI: [guide for Clojure projects](http://docs.travis-ci.com/user/languages/clojure/) with a one line file: `.travis.yml` per each project, containing `language: clojure` and enabling Travis service hook (can be administered in the Travis UI).

**Comment by alphaone** [comment]
Eventually, done! :)
